# SwiftLint Configuration for Swift 6
# https://github.com/realm/SwiftLint

# Swift version requirement
swift_version: "6.0"

# Paths to include in linting
included:
  - Sources
  - Tests
  - Examples

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - Package.swift
  - Sources/*/Resources
  - "*/Generated"
  - "*/Derived"

# Analyzer rules (requires compilation)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Enabled rules
opt_in_rules:
  # Swift 6 specific rules
  - strict_fileprivate
  - explicit_acl
  - explicit_top_level_acl
  - explicit_enum_raw_value
  - explicit_init
  
  # Concurrency rules (important for Swift 6)
  - actor_isolated_property
  - sendable_violation
  
  # Code quality rules
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_self
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Disabled rules (rules that are enabled by default but we want to disable)
disabled_rules:
  - todo # Allow TODO comments for now
  - line_length # Handled by SwiftFormat
  - trailing_whitespace # Handled by SwiftFormat

# Rule configurations
array_init:
  severity: error

attributes:
  always_on_same_line:
    - "@discardableResult"
    - "@objc"
    - "@MainActor"
    - "@Sendable"
  always_on_line_above:
    - "@available"

closure_end_indentation:
  severity: error

closure_spacing:
  severity: error

collection_alignment:
  align_colons: true

conditional_returns_on_newline:
  if_only: true

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

empty_count:
  severity: error
  only_after_dot: true

enum_case_associated_values_count:
  warning: 5
  error: 8

expiring_todo:
  approaching_expiry_severity: warning
  expired_severity: error
  approaching_expiry_days: 30
  expired_days: 90

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

file_name:
  severity: error
  excluded:
    - "main.swift"
    - "LinuxMain.swift"

file_name_no_space:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: warning

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8
  ignores_default_parameters: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - "id"
    - "URL"
    - "url"
    - "AI"
    - "ai"
    - "UI"
    - "ui"

implicit_return:
  included:
    - "closure"
    - "function"
    - "getter"

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

modifier_order:
  preferred_modifier_order:
    - "override"
    - "acl"
    - "setterACL"
    - "dynamic"
    - "mutating"
    - "lazy"
    - "final"
    - "required"
    - "convenience"
    - "typeMethods"
    - "owned"

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  allows_single_line: false

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 5
    error: 10

number_separator:
  minimum_length: 5
  minimum_fraction_length: 5

object_literal:
  image_literal: false
  color_literal: false

prefer_self_type_over_type_of_self:
  severity: error

private_outlet:
  allow_private_set: true

redundant_string_enum_value:
  severity: error

redundant_type_annotation:
  consider_default_literal_types_redundant: true

sorted_imports:
  severity: error

trailing_comma:
  mandatory_comma: true

type_body_length:
  warning: 250
  error: 400

type_contents_order:
  order:
    - "case"
    - "associated_type"
    - "type_alias" 
    - "subtype"
    - "type_property"
    - "ib_outlet"
    - "instance_property"
    - "ib_inspectable"
    - "initializer"
    - "type_method"
    - "view_life_cycle_method"
    - "ib_action"
    - "other_method"
    - "subscript"
    - "deinitializer"

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - "AI"
    - "UI"

vertical_parameter_alignment_on_call:
  severity: error

vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  # Swift 6 concurrency rules
  main_actor_usage:
    name: "MainActor Usage"
    regex: '@MainActor\s+(?!class|struct|enum|actor|func|var|let)'
    message: "@MainActor should be applied to types or members, not arbitrary code blocks"
    severity: warning

  sendable_conformance:
    name: "Sendable Conformance"
    regex: ':\s*Sendable\s*{'
    message: "Consider if this type truly needs Sendable conformance and is thread-safe"
    severity: warning

  # Prevent common Swift 6 migration issues
  global_actor_inconsistency:
    name: "Global Actor Inconsistency"
    regex: '@MainActor.*@MainActor'
    message: "Redundant @MainActor annotations"
    severity: error

  # Enforce proper async/await usage
  async_await_consistency:
    name: "Async/Await Consistency"
    regex: 'Task\s*\{'
    message: "Consider using structured concurrency instead of unstructured Task"
    severity: warning

# Reporter configuration
reporter: "xcode"